baseURL = 'https://stephanvanbiljon.github.io/'
languageCode = 'en-gb'
title = 'Stephans Site'
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[params]

name = 'Stephan van Biljon'